export default {
  at: '2022-10-04T20:10:14.975Z',
  products: [
    {
      description: 'mollit nostrud enim ut',
      name: 'eu',
      price: 860.46,
      tmpProperty: undefined,
      activePromoId: 67,
    },
    {},
    {},
    {},
    {
      description: 'nostrud duis laborum deserunt',
      name: 'fugiat',
      price: 660.13,
      tmpProperty: undefined,
      activePromoId: 36,
    },
    {},
    {},
    {},
    {},
    {},
    {
      description: 'amet culpa anim ea',
      name: 'non',
      price: 1193.62,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {},
    {},
    {},
    {
      description: 'culpa incididunt enim veniam',
      name: 'enim',
      price: 1352.53,
      tmpProperty: undefined,
      activePromoId: 90,
    },
    {
      description: 'ea veniam nostrud ipsum',
      name: 'id',
      price: 1899.21,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: 'magna labore culpa in',
      name: 'labore',
      price: 1712.38,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: 'tempor consectetur sunt deserunt',
      name: 'consectetur',
      price: 1268.59,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: 'laborum dolore id aliquip',
      name: 'officia',
      price: 1394.44,
      tmpProperty: undefined,
      activePromoId: 26,
    },
    {
      description: 'enim culpa commodo excepteur',
      name: 'ut',
      price: 503,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: 'minim pariatur aute laboris',
      name: 'adipisicing',
      price: 1270.23,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: 'consequat esse ea occaecat',
      name: 'ullamco',
      price: 141.19,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: 'dolore nulla incididunt nostrud',
      name: 'qui',
      price: 828.83,
      tmpProperty: undefined,
      activePromoId: 33,
    },
    {
      description: 'laboris velit aliqua nisi',
      name: 'dolore',
      price: 1815.91,
      tmpProperty: undefined,
      activePromoId: 48,
    },
    {
      description: 'culpa aliqua ea do',
      name: 'elit',
      price: 900.79,
      tmpProperty: undefined,
      activePromoId: 26,
    },
    {
      description: 'laboris labore irure ullamco',
      name: 'elit',
      price: 436.05,
      tmpProperty: undefined,
      activePromoId: 13,
    },
    {
      description: 'et labore Lorem esse',
      name: 'aliqua',
      price: 1912.03,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: 'elit dolore sunt laborum',
      name: 'sunt',
      price: 578.07,
      tmpProperty: undefined,
      activePromoId: 4,
    },
    {
      description: 'incididunt est proident id',
      name: 'voluptate',
      price: 1756.21,
      tmpProperty: undefined,
      activePromoId: 52,
    },
    {
      description: 'excepteur fugiat cupidatat reprehenderit',
      name: 'magna',
      price: 1421.4,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: 'velit aliqua ipsum est',
      name: 'sit',
      price: 1655.11,
      tmpProperty: undefined,
      activePromoId: 53,
    },
    {
      description: 'adipisicing officia reprehenderit deserunt',
      name: 'irure',
      price: 1583.14,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: 'enim esse minim tempor',
      name: 'et',
      price: 1877.78,
      tmpProperty: undefined,
      activePromoId: 2,
    },
    {
      description: 'nostrud elit quis ut',
      name: 'cillum',
      price: 1428.46,
      tmpProperty: undefined,
      activePromoId: 30,
    },
    {
      description: 'excepteur do adipisicing reprehenderit',
      name: 'enim',
      price: 584.81,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: 'cupidatat mollit laboris amet',
      name: 'minim',
      price: 1319.08,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: 'amet reprehenderit enim pariatur',
      name: 'nisi',
      price: 283.58,
      tmpProperty: undefined,
      activePromoId: 91,
    },
    {
      description: 'consequat tempor non eiusmod',
      name: 'labore',
      price: 122.95,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: 'reprehenderit elit quis aliqua',
      name: 'cupidatat',
      price: 1842.92,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: 'sint dolore pariatur eu',
      name: 'et',
      price: 599.91,
      tmpProperty: undefined,
      activePromoId: 73,
    },
    {
      description: 'cillum duis nulla excepteur',
      name: 'Lorem',
      price: 687.39,
      tmpProperty: undefined,
      activePromoId: 14,
    },
    {
      description: 'qui reprehenderit voluptate id',
      name: 'magna',
      price: 1250.28,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: 'cillum ex incididunt sint',
      name: 'do',
      price: 1152.99,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: 'ipsum adipisicing nisi consectetur',
      name: 'velit',
      price: 1936.07,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: 'non incididunt sint laborum',
      name: 'velit',
      price: 1699.84,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: 'ad incididunt voluptate non',
      name: 'cupidatat',
      price: 904.86,
      tmpProperty: undefined,
      activePromoId: 2,
    },
    {
      description: 'consequat incididunt cillum sint',
      name: 'enim',
      price: 1439.7,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: 'irure ad tempor cupidatat',
      name: 'velit',
      price: 1946.74,
      tmpProperty: undefined,
      activePromoId: 68,
    },
    {
      description: 'aliquip nostrud ex enim',
      name: 'quis',
      price: 897.64,
      tmpProperty: undefined,
      activePromoId: 35,
    },
    {
      description: 'amet consequat commodo in',
      name: 'laborum',
      price: 231.38,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: 'dolore in elit dolor',
      name: 'deserunt',
      price: 797.18,
      tmpProperty: undefined,
      activePromoId: 86,
    },
    {
      description: 'eiusmod laboris eiusmod minim',
      name: 'reprehenderit',
      price: 890.99,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: 'ullamco Lorem elit ipsum',
      name: 'dolor',
      price: 1301.38,
      tmpProperty: undefined,
      activePromoId: 99,
    },
    {
      description: 'reprehenderit labore dolore dolor',
      name: 'sint',
      price: 1887.49,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: 'qui eiusmod deserunt aliqua',
      name: 'dolor',
      price: 726.44,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: 'aliqua tempor nisi cupidatat',
      name: 'esse',
      price: 1730.48,
      tmpProperty: undefined,
      activePromoId: 63,
    },
    {
      description: 'commodo mollit exercitation deserunt',
      name: 'amet',
      price: 1491.51,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: 'aliqua eiusmod labore veniam',
      name: 'sit',
      price: 266.96,
      tmpProperty: undefined,
      activePromoId: 52,
    },
    {
      description: 'non ut mollit proident',
      name: 'excepteur',
      price: 573.68,
      tmpProperty: undefined,
      activePromoId: 69,
    },
    {
      description: 'veniam et nulla aute',
      name: 'velit',
      price: 1329.18,
      tmpProperty: undefined,
      activePromoId: 9,
    },
    {
      description: 'adipisicing sunt proident Lorem',
      name: 'consectetur',
      price: 541.66,
      tmpProperty: undefined,
      activePromoId: 36,
    },
    {
      description: 'adipisicing pariatur aliquip culpa',
      name: 'anim',
      price: 1971.36,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: 'sint nisi est dolor',
      name: 'do',
      price: 1082.19,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: 'do nostrud culpa reprehenderit',
      name: 'adipisicing',
      price: 1166.91,
      tmpProperty: undefined,
      activePromoId: 61,
    },
    {
      description: 'excepteur fugiat deserunt proident',
      name: 'ex',
      price: 1891.18,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: 'nostrud ipsum laboris voluptate',
      name: 'ea',
      price: 232.17,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: 'ea esse non enim',
      name: 'qui',
      price: 1574.18,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: 'excepteur proident consectetur cillum',
      name: 'laboris',
      price: 1565.76,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: 'incididunt proident amet dolor',
      name: 'aliqua',
      price: 214.67,
      tmpProperty: undefined,
      activePromoId: 30,
    },
    {
      description: 'occaecat labore fugiat est',
      name: 'aliqua',
      price: 593.84,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: 'exercitation dolore nostrud magna',
      name: 'irure',
      price: 1796.79,
      tmpProperty: undefined,
      activePromoId: 30,
    },
    {
      description: 'fugiat quis adipisicing aute',
      name: 'magna',
      price: 179.1,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: 'commodo aliqua ipsum excepteur',
      name: 'culpa',
      price: 771.91,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: 'cupidatat duis ipsum tempor',
      name: 'aliqua',
      price: 1440.04,
      tmpProperty: undefined,
      activePromoId: 18,
    },
    {
      description: 'est et aliquip reprehenderit',
      name: 'magna',
      price: 861.95,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: 'pariatur Lorem magna cillum',
      name: 'quis',
      price: 974.1,
      tmpProperty: undefined,
      activePromoId: 92,
    },
    {
      description: 'nisi anim non velit',
      name: 'ullamco',
      price: 1978.02,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: 'elit reprehenderit enim ea',
      name: 'do',
      price: 1364.55,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: 'irure consequat in consequat',
      name: 'laboris',
      price: 1641.18,
      tmpProperty: undefined,
      activePromoId: 53,
    },
    {
      description: 'in sit aute enim',
      name: 'voluptate',
      price: 1375.26,
      tmpProperty: undefined,
      activePromoId: 14,
    },
    {
      description: 'ullamco elit aliquip cillum',
      name: 'laborum',
      price: 591.61,
      tmpProperty: undefined,
      activePromoId: 86,
    },
    {
      description: 'dolor culpa exercitation aliquip',
      name: 'officia',
      price: 1314.94,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: 'elit irure sit sint',
      name: 'nisi',
      price: 1676.97,
      tmpProperty: undefined,
      activePromoId: 72,
    },
    {
      description: 'duis aliqua deserunt elit',
      name: 'eu',
      price: 1327.89,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: 'dolor Lorem aliquip commodo',
      name: 'consectetur',
      price: 1990.21,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: 'cillum do pariatur non',
      name: 'enim',
      price: 1735.59,
      tmpProperty: undefined,
      activePromoId: 7,
    },
    {
      description: 'nulla sunt commodo sint',
      name: 'proident',
      price: 1758.29,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: 'voluptate officia ad duis',
      name: 'commodo',
      price: 1450.5,
      tmpProperty: undefined,
      activePromoId: 28,
    },
    {
      description: 'dolore laborum in ex',
      name: 'cillum',
      price: 628.18,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: 'ullamco anim est nulla',
      name: 'et',
      price: 881.36,
      tmpProperty: undefined,
      activePromoId: 55,
    },
    {
      description: 'velit quis elit officia',
      name: 'do',
      price: 338.22,
      tmpProperty: undefined,
      activePromoId: 43,
    },
    {
      description: 'quis amet in veniam',
      name: 'ea',
      price: 1480.38,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: 'ut est ad ipsum',
      name: 'ad',
      price: 1559.66,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: 'magna eiusmod ullamco quis',
      name: 'labore',
      price: 1902.22,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: 'velit in labore est',
      name: 'dolor',
      price: 292.04,
      tmpProperty: undefined,
      activePromoId: 67,
    },
    {
      description: 'ea pariatur aute anim',
      name: 'irure',
      price: 1399.52,
      tmpProperty: undefined,
      activePromoId: 53,
    },
    {
      description: 'adipisicing laboris nulla velit',
      name: 'exercitation',
      price: 1834.82,
      tmpProperty: undefined,
      activePromoId: 81,
    },
    {
      description: 'culpa aliqua eiusmod sint',
      name: 'ipsum',
      price: 1087.85,
      tmpProperty: undefined,
      activePromoId: 61,
    },
    {
      description: 'mollit qui nulla qui',
      name: 'cillum',
      price: 1250.19,
      tmpProperty: undefined,
      activePromoId: 24,
    },
    {
      description: 'id ad est incididunt',
      name: 'est',
      price: 1245.93,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: 'aute magna ipsum elit',
      name: 'exercitation',
      price: 512.18,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: 'sint culpa magna in',
      name: 'ex',
      price: 965.72,
      tmpProperty: undefined,
      activePromoId: 2,
    },
    {
      description: 'nostrud aute nostrud elit',
      name: 'deserunt',
      price: 893.69,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: 'sint in ea do',
      name: 'officia',
      price: 470.56,
      tmpProperty: undefined,
      activePromoId: 9,
    },
    {
      description: 'veniam consequat deserunt non',
      name: 'mollit',
      price: 268.65,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: 'esse eiusmod ut dolore',
      name: 'sint',
      price: 900.25,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: 'laboris dolor id eu',
      name: 'id',
      price: 370.15,
      tmpProperty: undefined,
      activePromoId: 10,
    },
    {
      description: 'irure adipisicing aliqua laboris',
      name: 'Lorem',
      price: 1848.36,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: 'est fugiat irure commodo',
      name: 'proident',
      price: 901.86,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: 'consequat cupidatat ullamco nulla',
      name: 'eiusmod',
      price: 158.59,
      tmpProperty: undefined,
      activePromoId: null,
    },
    {
      description: 'ad magna minim aliqua',
      name: 'eu',
      price: 540.43,
      tmpProperty: undefined,
      activePromoId: null,
    },
  ],
}
